@NotificationSystem_HostAddress = http://localhost:5138

POST {{NotificationSystem_HostAddress}}/api/orders
Content-Type: application/json

{
  "GoodName": "Pizza",
  "Preferences": {
    "notificationChannelTypes": [1, 2]
  }
}
###
